In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%pip install scikit-learn
from sklearn.feature_selection import SelectKBest,f_classif,f_regression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
#Data Exploration and Preprocessing

df=pd.read_csv("https://raw.githubusercontent.com/GeethaGunasekaran1/Dataset_rep/refs/heads/main/crowdfunding.csv")

In [ ]:
df.head()

,Unnamed: 0,CampaignID,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
0,0,CID_00000,76159,73518.028955,15,1903,Film,September,Australia,GBP,11,Yes,41758,3,0
1,1,CID_00001,69394,60068.683288,49,469,Art,October,Australia,GBP,7,Yes,79112,48,0
2,2,CID_00002,18652,22958.153470,58,148,Film,February,USA,EUR,17,No,3942,9,1
3,3,CID_00003,19487,24229.048390,39,780,Film,October,Germany,AUD,10,No,22047,35,1
4,4,CID_00004,26734,17984.630311,68,1622,Games,September,Australia,AUD,12,Yes,72568,17,0

In [ ]:
df.tail()

,Unnamed: 0,CampaignID,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
99995,99995,CID_99995,80417,112068.932642,26,870,Music,October,UK,AUD,6,No,84173,8,1
99996,99996,CID_99996,85052,100430.502040,78,1146,Film,October,USA,USD,8,No,13913,42,1
99997,99997,CID_99997,68407,102020.936312,87,636,Art,March,UK,EUR,2,Yes,45273,13,1
99998,99998,CID_99998,59749,67026.111706,51,1276,Music,August,Australia,CAD,10,Yes,67574,29,1
99999,99999,CID_99999,39913,54863.288105,73,695,Film,April,Germany,CAD,11,No,84806,41,1

In [ ]:
df=df.drop(columns=['CampaignID','Unnamed: 0'])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   GoalAmount           100000 non-null  int64
 1   RaisedAmount         100000 non-null  float64
 2   DurationDays         100000 non-null  int64
 3   NumBackers           100000 non-null  int64
 4   Category             100000 non-null  str
 5   LaunchMonth          100000 non-null  str
 6   Country              100000 non-null  str
 7   Currency             100000 non-null  str
 8   OwnerExperience      100000 non-null  int64
 9   VideoIncluded        100000 non-null  str
 10  SocialMediaPresence  100000 non-null  int64
 11  NumUpdates           100000 non-null  int64
 12  IsSuccessful         100000 non-null  int64
dtypes: float64(1), int64(7), str(5)
memory usage: 9.9 MB

In [ ]:
df.describe

<bound method NDFrame.describe of        GoalAmount   RaisedAmount  DurationDays  NumBackers Category  \
0           76159   73518.028955            15        1903     Film
1           69394   60068.683288            49         469      Art
2           18652   22958.153470            58         148     Film
3           19487   24229.048390            39         780     Film
4           26734   17984.630311            68        1622    Games
...           ...            ...           ...         ...      ...
99995       80417  112068.932642            26         870    Music
99996       85052  100430.502040            78        1146     Film
99997       68407  102020.936312            87         636      Art
99998       59749   67026.111706            51        1276    Music
99999       39913   54863.288105            73         695     Film

      LaunchMonth    Country Currency  OwnerExperience VideoIncluded  \
0       September  Australia      GBP               11           Yes
1         October  Australia      GBP                7           Yes
2        February        USA      EUR               17            No
3         October    Germany      AUD               10            No
4       September  Australia      AUD               12           Yes
...           ...        ...      ...              ...           ...
99995     October         UK      AUD                6            No
99996     October        USA      USD                8            No
99997       March         UK      EUR                2           Yes
99998      August  Australia      CAD               10           Yes
99999       April    Germany      CAD               11            No

       SocialMediaPresence  NumUpdates  IsSuccessful
0                    41758           3             0
1                    79112          48             0
2                     3942           9             1
3                    22047          35             1
4                    72568          17             0
...                    ...         ...           ...
99995                84173           8             1
99996                13913          42             1
99997                45273          13             1
99998                67574          29             1
99999                84806          41             1

[100000 rows x 13 columns]>

In [ ]:
df.shape

(100000, 13)

In [ ]:
print(df.isnull().sum())

GoalAmount             0
RaisedAmount           0
DurationDays           0
NumBackers             0
Category               0
LaunchMonth            0
Country                0
Currency               0
OwnerExperience        0
VideoIncluded          0
SocialMediaPresence    0
NumUpdates             0
IsSuccessful           0
dtype: int64

In [ ]:
df=df.drop_duplicates()
print(df.duplicated().sum())

0

In [ ]:
num_cols=df.select_dtypes(include=np.number)
cat_cols=df.select_dtypes(include=object)

C:\Users\apisr\AppData\Local\Temp\ipykernel_33676\1052451562.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols=df.select_dtypes(include=object)

In [ ]:
#statistical summary

summary = num_cols.agg(['max','median','min','mean','std']).T
print(summary)

                               max        median          min          mean  \
GoalAmount            99999.000000  50706.000000  1000.000000  50538.001310
RaisedAmount         149238.361559  45980.674476   528.632349  50598.121803
DurationDays             89.000000     52.000000    15.000000     52.047370
NumBackers             1999.000000   1003.000000    10.000000   1003.347340
OwnerExperience          19.000000      9.000000     0.000000      9.489130
SocialMediaPresence   99999.000000  50024.500000   100.000000  50077.301010
NumUpdates               49.000000     25.000000     0.000000     24.483230
IsSuccessful              1.000000      1.000000     0.000000      0.500940

                              std
GoalAmount           28613.822592
RaisedAmount         33255.277493
DurationDays            21.653238
NumBackers             574.485153
OwnerExperience          5.763538
SocialMediaPresence  28767.521522
NumUpdates              14.413833
IsSuccessful             0.500002

In [ ]:
#encoding

cols_to_encode = ['Category', 'LaunchMonth',
                  'Country', 'Currency',
                  'VideoIncluded']
le=LabelEncoder()
for col in cols_to_encode:
    df[col]=le.fit_transform(df[col])

In [ ]:
df.head()

,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
0,76159,73518.028955,15,1903,1,11,0,3,11,1,41758,3,0
1,69394,60068.683288,49,469,0,10,0,3,7,1,79112,48,0
2,18652,22958.153470,58,148,1,3,4,2,17,0,3942,9,1
3,19487,24229.048390,39,780,1,10,2,0,10,0,22047,35,1
4,26734,17984.630311,68,1622,2,11,0,0,12,1,72568,17,0

In [ ]:
X=df.drop(columns=['IsSuccessful'])
y=df['IsSuccessful']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#Feature Selection
selector=SelectKBest(score_func=f_classif,k=6)
X_train=selector.fit_transform(X_train,y_train)
X_test = selector.transform(X_test)

In [ ]:
selected_cols=X.columns[selector.get_support()]
print(selected_cols)

Index(['GoalAmount', 'RaisedAmount', 'DurationDays', 'OwnerExperience',
       'VideoIncluded', 'NumUpdates'],
      dtype='str')

In [ ]:
X_train.shape

(80000, 6)

In [ ]:
X_test.shape

(20000, 6)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_trained_scaled = scaler.fit_transform(X_train)
X_tested_scaled = scaler.transform(X_test)

In [ ]:
#Classification model building:

#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=200,random_state=42)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [ ]:
y_pred_rf=rf.predict(X_test)

In [ ]:
accuracy_rf= accuracy_score(y_test,y_pred_rf)
print(f"Random Forest Accuracy : {accuracy_rf:.4f}")

Random Forest Accuracy : 0.9876

In [ ]:
report_rf=classification_report(y_test,y_pred_rf)
print("Classication Report for Random Forest Model\n")
print(report_rf)

Classication Report for Random Forest Model

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      9953
           1       0.99      0.99      0.99     10047

    accuracy                           0.99     20000
   macro avg       0.99      0.99      0.99     20000
weighted avg       0.99      0.99      0.99     20000

In [ ]:
print(confusion_matrix(y_test,y_pred_rf))

[[9850  103]
 [ 145 9902]]

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_trained_scaled,y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_pred_Knn=knn.predict(X_tested_scaled)

In [ ]:
accuracy_knn=accuracy_score(y_test,y_pred_Knn)
print(f"Knn accuracy score: {accuracy_knn:.4f}")

Knn accuracy score: 0.8972

In [ ]:
report_knn=classification_report(y_test,y_pred_Knn)
print("Classication Report for Random Forest Model\n")
print(report_knn)

Classication Report for Random Forest Model

              precision    recall  f1-score   support

           0       0.90      0.90      0.90      9953
           1       0.90      0.90      0.90     10047

    accuracy                           0.90     20000
   macro avg       0.90      0.90      0.90     20000
weighted avg       0.90      0.90      0.90     20000

In [ ]:
print(confusion_matrix(y_test,y_pred_Knn))

[[8940 1013]
 [1043 9004]]

In [ ]:
#Decision Tree

from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion='gini',max_depth=7,random_state=42)
dtree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=7, random_state=42)

In [ ]:
y_pred_dtree=dtree.predict(X_test)

In [ ]:
accuracy_dtree=accuracy_score(y_test,y_pred_dtree)
print(f"Decision Tree accuracy score: {accuracy_dtree:.4f}")

report_dtree=classification_report(y_test,y_pred_dtree)
print("Classication Report for Random Forest Model\n")
print(report_dtree)

print("Decision Tree Confusion Matrix")
print(confusion_matrix(y_test,y_pred_dtree))

Decision Tree accuracy score: 0.8912
Classication Report for Random Forest Model

              precision    recall  f1-score   support

           0       0.84      0.96      0.90      9953
           1       0.96      0.82      0.88     10047

    accuracy                           0.89     20000
   macro avg       0.90      0.89      0.89     20000
weighted avg       0.90      0.89      0.89     20000

Decision Tree Confusion Matrix
[[9601  352]
 [1823 8224]]

Max depth value 7 is giving  accuracy values like 89.

Changing the criterion to Entropy also gave similar values. So im going with "Gini". There was no signifiance improvement in the Accuracy after changing the criterion to Entropy.

In [ ]:
#NaiveBayes Classifier

#using gaussian NB
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model.fit(X_train,y_train)

y_pred_nb=nb_model.predict(X_test)

accuracy_nb=accuracy_score(y_test,y_pred_nb)
print(f"Accuracy score gaussian NaiveBayes: {accuracy_nb:.4f}")

report_nb=classification_report(y_test,y_pred_nb)
print("Naive Bayes Classification Report:\n")
print(report_nb)

print(" NB Confusion Matrix")
print(confusion_matrix(y_test,y_pred_nb))

Accuracy score gaussian NaiveBayes: 0.6620
Naive Bayes Classification Report:

              precision    recall  f1-score   support

           0       0.62      0.81      0.70      9953
           1       0.73      0.52      0.61     10047

    accuracy                           0.66     20000
   macro avg       0.68      0.66      0.65     20000
weighted avg       0.68      0.66      0.65     20000

 NB Confusion Matrix
[[8049 1904]
 [4856 5191]]

Using Gaussian Naive bayes since we have numerical features.

In [ ]:
#SVM - linear
from sklearn.svm import SVC

svm_model=SVC(kernel= 'linear')
svm_model.fit(X_trained_scaled,y_train)

y_pred_svm=svm_model.predict(X_tested_scaled)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Accuracy score svm: {accuracy_svm:.4f}")

report_svm=classification_report(y_test,y_pred_svm)
print("SVM Classification Report:\n")
print(report_svm)

print("SVM Confusion Matrix")
print(confusion_matrix(y_test,y_pred_svm))

Accuracy score svm: 0.9991
Naive Bayes Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9953
           1       1.00      1.00      1.00     10047

    accuracy                           1.00     20000
   macro avg       1.00      1.00      1.00     20000
weighted avg       1.00      1.00      1.00     20000

SVM Confusion Matrix
[[ 9950     3]
 [   14 10033]]

In [ ]:
#SVM - rbf
from sklearn.svm import SVC
svm_model1=SVC(kernel= 'rbf')
svm_model1.fit(X_trained_scaled,y_train)
y_pred_svm1=svm_model1.predict(X_tested_scaled)
accuracy_svm1 = accuracy_score(y_test, y_pred_svm1)
print(f"Accuracy score svm: {accuracy_svm1:.4f}")

Accuracy score svm: 0.9870

evaluated both liner and rbf svm models. the accuracy is better with linear model.

In [ ]:
from sklearn.model_selection import cross_val_score
models = {"Random Forest" : RandomForestClassifier(random_state=42),
          "Decision trees" : DecisionTreeClassifier(random_state=42),
          "Naive Bayes" : GaussianNB()
}

for name,model in models.items():
    scores=cross_val_score(model,X_train,y_train,cv=5,scoring='accuracy')
    print(f"{name} : mean_scores = {scores.mean():.4f}")

Random Forest : mean_scores = 0.9862
Decision trees : mean_scores = 0.9923
Naive Bayes : mean_scores = 0.6646

In [ ]:
models_scaled = {"SVM" : SVC(),
          "KNN" : KNeighborsClassifier()
}

for name,model in models_scaled.items():
    scores=cross_val_score(model,X_trained_scaled,y_train,cv=5,scoring='accuracy')
    print(f"{name} : mean_scores = {scores.mean():.4f}")

SVM : mean_scores = 0.9852
KNN : mean_scores = 0.8922

In [ ]:
#HyperParameter Tuning

#Random forest model
from sklearn.model_selection import GridSearchCV

rf=RandomForestClassifier(random_state=42)

params={'n_estimators' : [50,100,200],
        'max_depth' : [5,10,15]}

grid=GridSearchCV(
    rf,
    params,
    cv=5,
    scoring='accuracy')

grid.fit(X_train,y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'max_depth': 15, 'n_estimators': 50}
Best CV Score: 0.9641500000000001

In [ ]:
best_rf = grid.best_estimator_
print(best_rf)

RandomForestClassifier(max_depth=15, n_estimators=50, random_state=42)

In [ ]:
#Knn model

from sklearn.model_selection import GridSearchCV

knn=KNeighborsClassifier()

params={'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
    }

grid=GridSearchCV(
    knn,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_trained_scaled,y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'}
Best CV Score: 0.897

In [ ]:
best_knn=grid.best_estimator_
print(best_knn)

KNeighborsClassifier(metric='manhattan', n_neighbors=11, weights='distance')

In [ ]:
#Decision Tree

from sklearn.model_selection import GridSearchCV

dtree=DecisionTreeClassifier(random_state=42)

params={'criterion': ['gini','entropy'],
        'max_depth': [3,5,7,9]
    }

grid=GridSearchCV(
    dtree,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train,y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'criterion': 'gini', 'max_depth': 9}
Best CV Score: 0.9279874999999999

In [ ]:
best_dtree=grid.best_estimator_
print(best_dtree)

DecisionTreeClassifier(max_depth=9, random_state=42)

In [ ]:
#Naive Bayes

from sklearn.model_selection import GridSearchCV

nb_model=GaussianNB()

params={'var_smoothing': [1e-12, 1e-11, 1e-10, 1e-9, 1e-8]
    }

grid=GridSearchCV(
    nb_model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_train,y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'var_smoothing': 1e-09}
Best CV Score: 0.6647624999999999

In [ ]:
best_nb_model=grid.best_estimator_
print(best_nb_model)

GaussianNB()

In [ ]:
#SVM

from sklearn.model_selection import GridSearchCV

svm_model=SVC(kernel= 'linear')

params={'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
    }

grid=GridSearchCV(
    svm_model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1)

grid.fit(X_trained_scaled,y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'C': 10, 'kernel': 'linear'}
Best CV Score: 0.9993500000000001

In [ ]:
best_svm=grid.best_estimator_
print(best_svm)

SVC(C=10, kernel='linear')

In [ ]:
models_compare = {
          "Random Forest" : best_rf,
          "Decision trees" : best_dtree,
          "Naive Bayes" : best_nb_model
}

results=[]

for name,model in models_compare.items():

    model.fit(X_train,y_train)
    pred=model.predict(X_test)

    report = classification_report(
        y_test,
        pred,
        output_dict=True
    )

    results.append({
        'Model' : name,
        'Accuracy' : accuracy_score(y_test,pred),
        'Precision' : report['weighted avg']['precision'],
        'Recall': report['weighted avg']['recall'],
        'F1-Score': report['weighted avg']['f1-score']
    })

results_df1 = pd.DataFrame(results)
print(results_df1)

            Model  Accuracy  Precision   Recall  F1-Score
0   Random Forest   0.95575   0.958145  0.95575  0.955700
1  Decision trees   0.92970   0.934319  0.92970  0.929531
2     Naive Bayes   0.66220   0.678243  0.66220  0.654886

In [ ]:
models_compare_scale = {
          "SVM" : best_svm,
          "KNN" : best_knn
}

results = []

for name,model in models_compare_scale.items():

    model.fit(X_trained_scaled,y_train)
    pred=model.predict(X_tested_scaled)

    report = classification_report(
        y_test, 
        pred,
        output_dict=True
    )

    results.append({
        'Model' : name,
        'Accuracy' : accuracy_score(y_test,pred),
        'Precision' : report['weighted avg']['precision'],
        'Recall': report['weighted avg']['recall'],
        'F1-Score': report['weighted avg']['f1-score']
    })
results_df = pd.DataFrame(results)
print(results_df)

  Model  Accuracy  Precision   Recall  F1-Score
0   SVM   0.99955   0.999550  0.99955  0.999550
1   KNN   0.89570   0.895775  0.89570  0.895699

In [ ]:
#model comparision

comparison_df = pd.concat([results_df1, results_df], ignore_index=True)

comparison_df = comparison_df.round(4)

print(comparison_df)

            Model  Accuracy  Precision  Recall  F1-Score
0   Random Forest    0.9558     0.9581  0.9558    0.9557
1  Decision trees    0.9297     0.9343  0.9297    0.9295
2     Naive Bayes    0.6622     0.6782  0.6622    0.6549
3             SVM    0.9996     0.9996  0.9996    0.9996
4             KNN    0.8957     0.8958  0.8957    0.8957

All classification models were evaluated using Accuracy, Precision, Recall, and F1-Score. Among the models tested, SVM achieved the highest performance with an accuracy of 99.96%, followed by Random Forest (95.58%) and Decision Tree (92.97%). KNN achieved moderate performance, while Naive Bayes produced the lowest accuracy.

Based on the evaluation metrics and cross-validation results, SVM was selected as the best-performing model for predicting crowdfunding campaign success. Its high accuracy and balanced Precision, Recall, and F1-Score indicate excellent classification performance on the dataset.

Confusion Matrix Analysis

The SVM model produced the best confusion matrix results, with only 17 misclassifications out of 20,000 test samples. This indicates excellent classification performance and explains its highest accuracy score of 99.96%.

Random Forest also performed well, correctly classifying most campaigns and making relatively few errors. Decision Tree achieved good performance but produced more false negatives compared to Random Forest and SVM.

KNN showed moderate performance with a higher number of misclassifications, resulting in lower accuracy. Naive Bayes had the highest number of classification errors, which led to the lowest accuracy among all models.

Overall, the confusion matrices confirm that SVM is the most effective model for predicting crowdfunding campaign success, followed by Random Forest and Decision Tree.

SVM

Strengths: Highest accuracy and best overall performance.

Weaknesses: Requires feature scaling and can be slower to train.

Improvements: Tune C and try different kernels.

Random Forest

Strengths: High accuracy and handles complex data well.

Weaknesses: Harder to interpret than a Decision Tree.

Improvements: Tune n_estimators and max_depth.

Decision Tree

Strengths: Simple, easy to understand, and fast.

Weaknesses: Can overfit the data.

Improvements: Adjust tree depth and pruning settings.

KNN

Strengths: Simple and effective after scaling.

Weaknesses: Sensitive to the choice of k.

Improvements: Optimize n_neighbors and distance metrics.

Naive Bayes

Strengths: Fast and easy to implement.

Weaknesses: Assumes features are independent.

Improvements: Tune var_smoothing and improve feature selection.

Conclusion

SVM achieved the best performance and was selected as the final model. Random Forest and Decision Tree also performed well, while KNN showed moderate performance. Naive Bayes had the lowest accuracy.